on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Devendra Portfolio
        uses: devendra545/SE@main
        with:
          source: SE/notebooks
          dependencies: requirements.txt